### ISSUE TITLE
StyleProp wrong type

### ISSUE THREAD

**Issue by branikclimbs** [JonnyBurger/touchable-scale#3]
Hi, I think style prop type should be 
`style?: StyleProp<ViewStyle>`
instead of 
`style?: ViewStyle`

Right now you cannot pass array of styles into style prop like this `style={[ style, anotherStyle ]}` (only if you use StyleSheet.flatten) because you will get ts error `Type 'any[]' has no properties in common with type 'ViewStyle'`

**Comment by JonnyBurger** [comment]
Thanks, fixed in v1.0.2!
